# apiVersion: v1
# kind: Pod
# metadata:
#   name: csgo-test
#   labels:
#     app: csgo-test
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csgo-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: csgo-test
  serviceName: csgo-test
  template:
    metadata:
      labels:
        app: csgo-test
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9273'
    spec:
      nodeName: "161739"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "rm -f /home/csgo/server/csgo/console.log; ln -s /dev/stdout /home/csgo/server/csgo/console.log"]
        volumeMounts:
        - mountPath: /home/csgo/server
          name: csgo-volume
      containers:
      - image: timche/csgo
        resources:
          requests:
            memory: "4G"
            cpu: "2"
          limits:
            cpu: "2"
        command: ["/home/csgo/server.sh", "start"]
        name: csgo-test
        ports:
        - containerPort: 27015
        - containerPort: 27020
        env:
        - name: CSGO_DISABLE_BOTS
          value: "true"
        - name: CSGO_GSLT
          value: "6130C8F3A2D6C94EDF37A66044BA2D1C"
        - name: CSGO_MAX_PLAYERS
          value: "12"
        - name: CSGO_IP
          value: "0.0.0.0"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSGO_PARAMS
          #value: "+sv_hibernate_when_empty 0 +log on +sv_log_onefile 1 +sv_logecho 1 +sv_logbans 1 +sv_logfile 1 -condebug -secure"
          value: "+sv_hibernate_when_empty 0 -condebug -secure"
        volumeMounts:
        - mountPath: /home/csgo/server
          name: csgo-volume
          readOnly: true
        - mountPath: /home/csgo/server/csgo/logs
          name: logs-volume
      - image: telegraf:1.20-alpine
        name: csgo-metrics
        ports:
        - containerPort: 9273
        env:
          - name: CSGO_IP_PORT
            value: "127.0.0.1:27015"
          - name: CSGO_RCON
            value: "changeme"
        volumeMounts:
        - name: csgo-telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "csgo"
        effect: "NoSchedule"
      nodeSelector:
        type: csgo
      volumes:
      - name: logs-volume
        emptyDir: {}
      - name: csgo-volume
        hostPath:
          # directory location on host
          path: /home/npfuser
          # this field is optional
          type: Directory
      - name: csgo-telegraf-config
        configMap:
          name: csgo-telegraf-config
          items:
            - key: telegraf.conf
              path: telegraf.conf
---
apiVersion: v1
kind: Service
metadata:
  name: csgo-test
spec:
  selector:
    app: csgo-test
  ports:
    - name: gametcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: gameudp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: matchandhltvtcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: matchandhltvudp
      protocol: UDP
      port: 27020
      targetPort: 27020
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo-telegraf-config
data:
  telegraf.conf: |
    [agent]
      ## Default data collection interval for all inputs
      interval = "60s"

    [[inputs.csgo]]
      servers = [
            ["${CSGO_IP_PORT}", "${CSGO_RCON}"]
      ]

    [[outputs.prometheus_client]]
      ## Address to listen on.
      listen = ":9273"
